# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination berdasarkan jumlah post
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown

permalink: "/:title"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Catatan Mahasiswa
      
# Deskripsi blog
description: Blog Mahasiswa Sederhana
author: 
  name: sofian
  email: id.sofiangrh@gmail.com
  github: sofiangrh
  twitter: sofiangrh
  pinterest: sofiangrh
  linkedin: sofiangrh
  bio: Udah gak gondrong. Pengguna OSS.
  email_md5: 07ba8e922d64fd7f79f31fce97928b0a

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

# Bantuan pengaturan komentar
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.

comments :
    provider : disqus
    disqus :
      short_name : mahasiswasederhana
    livefyre :
      site_id :
    intensedebate :
      account :
    facebook :
      appid :
      num_posts:
      width:
      colorscheme:
