# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: true
markdown: kramdown

permalink: "/:title"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Catatan Mahasiswa

description: Blog Mahasiswa Sederhana
author: 
  name: sofian
  email: sofian.nugraha@yahoo.com
  github: sofianugraha
  twitter: sofiangrh
  pinterest: sofiangrh
  linkedin: sofian-nugraha
  bio: Seorang Manusia. Mahasiswa Sederhana. Pengguna OSS. 
  email_md5: 07ba8e922d64fd7f79f31fce97928b0a

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments :
    provider : disqus
    disqus :
      short_name : mahasiswasederhana
    livefyre :
      site_id :
    intensedebate :
      account :
    facebook :
      appid :
      num_posts:
      width:
      colorscheme:
